const data=[
    {
        id:1,
        img:'/images/team/team-copyright-1-1.jpg',
        title:'Adam Groover',
        p:'Professional barber and tattoo master is ready to create your perfect style',
        email:'grooveradam@example.com',
        job:'Stylist',
    },
    {
        id:2,
        img:'/images/team/team-copyright-2-2.jpg',
        title:'David Hammer',
        p:'Expert stylist who sticks to the old saying "When you look good you feel good"',
        email:'hammer@example.com',
        job:'Assistant Manager',
    },
    {
        id:3,
        img:'/images/team/team-copyright-3-3-1.jpg',
        title:'Sam York',
        p:'Master barber with a true passion for the art of grooming and image making',
        email:'york@example.com',
        job:'Master Barber',
    },
    {
        id:4,
        img:'/images/team/team-copyright-5-5.jpg',
        title:'Jenny Wallace',
        p:'Talented barber working with all hair types, genders, ages and ethnicities',
        email:'jenny@example.com',
        job:'Talented barber',
    },
    {
        id:5,
        img:'/images/team/team-copyright-6-6.jpg',
        title:'Jay Adams',
        p:'Highly experienced master with all aspects of cutting hair and wet shaving',
        email:'jay@example.com',
        job:'Highly experienced master',
    },
    {
        id:6,
        img:'/images/team/team-copyright-7-7.jpg',
        title:'Alex Norman',
        p:'Expert at both long and short clean cuts with excellent beard styling skills',
        email:'alex@example.com',
        job:'Expert Burber',
    },
    {
        id:7,
        img:'/images/team/team-copyright-8-8.jpg',
        title:'Andrew Garfield',
        p:'Professional stylist who loves making people look and feel great every day',
        email:'andrew@example.com',
        job:'Professional stylist',
    },
    {
        id:8,
        img:'/images/team/team-copyright-9.jpg',
        title:'Michael May',
        p:'Saving the world from bad haircuts, Michael has been cutting hair since the 90s',
        email:'mmay@example.com',
        job:'Stylist',
    },
]
export default data